added err

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,7 +12,7 @@ on:
 jobs:
   check:
     runs-on: ubuntu-latest
-    
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -47,11 +47,11 @@ jobs:
           script: |
             if [ -d "${{ env.MASTER_DIR }}/.git" ]; then
               echo "Found repository. Pulling..."
-              git pull origin release
+              git pull origin release || echo "Failed to pull repository." && exit 1
               echo "Repository is updated."
             else
               echo "Repository is not pulled. Pulling..."
-              git clone ${{ github.repositoryUrl }} -b release --single-branch ${{ env.MASTER_DIR }}
+              git clone ${{ github.repositoryUrl }} -b release --single-branch ${{ env.MASTER_DIR }} || echo "Failed to pull repository." && exit 1
               echo "Repository is pulled."
             fi
 
