fixx

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,7 +51,7 @@ jobs:
               echo "Repository is updated."
             else
               echo "Repository is not pulled. Pulling..."
-              git clone ${{ github.repositoryUrl }} -b release --single-branch ${{ env.MASTER_DIR }} || echo "Failed to pull repository." && exit 1
+              git clone ${{ github.repositoryUrl }} -b release ${{ env.MASTER_DIR }} || echo "Failed to pull repository." && exit 1
               echo "Repository is pulled."
             fi
 
